DATA_DIR: "<cityscapes_folder>"
NUM_WORKERS: 12
VALIDATE: True
METHOD_TYPE: "VT"
METHOD_NAME: "vt_cityscapes"
DATASET_STRUCTURE:
  DATASET_NAME: "cityscapes"
  IMAGE: "leftImg8bit"
  IMAGE_EXT: "png"
  PANOPTIC: "gtFine_panoptic"
  PANOPTIC_EXT: "png"
  ANGLE: "gtFine_angle"
  ANGLE_EXT: "png"
  DT: "gtFine_dt"
  DT_EXT: "png"
AUGMENTATIONS:
  MIN_SIZE_TRAIN: [512, 640, 704, 832, 896, 1024, 1152, 1216, 1344, 1408, 1536, 1664, 1728, 1856, 1920, 2048]
  MAX_SIZE_TRAIN: 4096
  MIN_SIZE_TRAIN_SAMPLING: 'choice'
  FLIP_PROB: 0.5
  CROP:
    ENABLED: True
    TYPE: 'absolute'
    SIZE: [512, 512]
  NORMALIZE:
    MEAN: [123.675, 116.280, 103.530]
    STD: [58.395, 57.120, 57.375]
NETWORK:
  ARCHITECTURE: "hrnet32_boundary_net"
  LEARNING_RATE: 0.001
  SCHEDULER: "WarmupPolyLR"
  LOAD_CHECKPOINT: False
  CHECKPOINT: ""
  OUTPUT_SIZE: 2
  BOUNDARY_LOSS_WEIGHT: 10.0
  NUM_ITERATIONS: 120000
DIVERGENCE_THRESHOLD: -0.8
