DATA_DIR: "<synthia_folder>"
NUM_WORKERS: 12
VALIDATE: True
METHOD_TYPE: "VT"
METHOD_NAME: "vt_synthia"
DATASET_STRUCTURE:
  DATASET_NAME: "synthia"
  IMAGE: "RGB"
  IMAGE_EXT: "png"
  PANOPTIC: "GT/COLOR"
  PANOPTIC_EXT: "png"
  ANGLE: "GT/ANGLE"
  ANGLE_EXT: "png"
  DT: "GT/DT"
  DT_EXT: "png"
AUGMENTATIONS:
  MIN_SIZE_TRAIN: [380, 456, 532, 608, 684, 760, 836, 912, 988, 1064, 1140, 1216, 1292, 1368, 1444, 1520]
  MAX_SIZE_TRAIN: 2560
  MIN_SIZE_TRAIN_SAMPLING: 'choice'
  FLIP_PROB: 0.5
  CROP:
    ENABLED: True
    TYPE: 'absolute'
    SIZE: [380, 640]
  NORMALIZE:
    MEAN: [123.675, 116.280, 103.530]
    STD: [58.395, 57.120, 57.375]
NETWORK:
  ARCHITECTURE: "hrnet32_boundary_net"
  LEARNING_RATE: 0.001
  SCHEDULER: "WarmupPolyLR"
  LOAD_CHECKPOINT: False
  CHECKPOINT: ""
  OUTPUT_SIZE: 2
  BOUNDARY_LOSS_WEIGHT: 10.0
  NUM_ITERATIONS: 120000
DIVERGENCE_THRESHOLD: -0.8
